server {
  listen       80;
  server_tokens off;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy same-origin always;
  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}
