services:
  db:
    image: postgres:12.22-alpine
    environment:
      POSTGRES_DB: bookit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: "Europe/Stockholm"
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:5.0.14-alpine
    ports:
      - 127.0.0.1:6379:6379

  db-scripts: # Deletes personal data from database
    build:
      context: ./db-scripts
      dockerfile: Dockerfile
    environment:
      PGPASSWORD: password
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bookit
