version: "3"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: bookit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: "Europe/Stockholm"
    ports:
      - 5432:5432

  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  db-scripts: # Deletes personal data from database
    build:
      context: ./db-scripts
      dockerfile: Dockerfile
    environment:
      PGPASSWORD: password
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bookit
